pool:
  name: 'My Pool'  # Use your self-hosted agent pool name

steps:
  - task: UseDotNet@2  # This is an easy task to test
    inputs:
      packageType: 'sdk'
      version: '6.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - script: |
      echo "This is a test pipeline running on my self-hosted agent!"
      echo "Agent name: $(Agent.Name)"
    displayName: 'Test Script'
